### PR TITLE
Test to fix #144

### LINKED ISSUE #144: Broken Algae recipes with Omnienergy
With Angelsbioprocessing + Bobplates + Omnienergy:

image

How it should look like:

image

### PR DESCRIPTION
**Pull request by Pezzawinkle**
Creating draft PR, in prep for merge
This is a tweak to the recipe standardisation function be more even more flexible than it already is...

soo many edge cases...

Fixes #144

### CODE REVIEW

**Comment by SqFKYo** [comment]
My Brown Algae is still broken unfortunately.

**Comment by Samuel2507** [comment]
Icon and Loc. Name should be fixed now, getting icon errors though...

**Comment by Samuel2507** [comment]
With  
https://github.com/Arch666Angel/mods/issues/212
fixed, this PR seems to work fine now

**Comment by Samuel2507** [comment]
Fixes #144

**Pull request merged**
