### PR TITLE
Omnifurnace rebalancing

### PR DESCRIPTION
**Pull request by SqFKYo**
Moved omnibrick from omnicrystal to omnimatter.
Omnifurnace now needs omnibricks instead of stone bricks.
Hand made omnicium plates and omnibricks now need a tad less materials to reduce the tedium of very early game, while still feeling challenging.

### CODE REVIEW

**Comment by SqFKYo** [comment]
Accidentally added dead code, fixing.

**Comment by SqFKYo** [comment]
Should be OK now!

**Comment by Pezzawinkle** [comment]
I would recommend also moving the graphics for the purple path to omnimatter, and update the file with the new location, you should only ever call graphics in "required" mods

**Comment by SqFKYo** [comment]
omnimatter_crystal/graphics/icons/omnite-brick.png → omnimatter/graphics/icons/omnite-brick.png
This is done already if you meant this :-)

**Comment by SqFKYo** [comment]
Finally understood what you meant, thanks for good review!

**Pull request merged**
