### PR TITLE
Omni energy compat options

### PR DESCRIPTION
**Pull request by Pezzawinkle**
Proposed changes to Omnienergy (with bobs burner phase)

### CODE REVIEW

**Comment by Pezzawinkle** [comment]
FFS, why did that not rebase correctly...

**Comment by Pezzawinkle** [comment]
For some reason i cannot remove the burner lab recipe correctly...

**Comment by SqFKYo** [comment]
I'd suggest instead of removing burner lab from lab, we'd replace it with omnitor lab.
And add an exception to standardization for steam sp, so the omnimatter Steam SP fix works again.

**Comment by Samuel2507** [comment]
Looking good, just have a few minor things i would tweak:

-Simple Automation (10 SP) -->Burner automation(5 SP)  --> Basic Belts (25 SP) : Buner automation tech cost should be increased to fit betweent he other 2, maybe to 15SP?

-Steam powered automation currently has Burner automation as direct AND indirect  prereq. I would remove the direct prereq

-Steam, Steam powered automation and red science SP cost seems too low aswell compared to its prereq

"--tempted to move steam-engine behind green in the interim"
-I would totally do that because:
--without bobs burner phase its behind green aswell
--you only have to use the heat burner as electricity source for a short moment  otherwise

**Comment by SqFKYo** [comment]
I agree with Sam's comments. I also want to make it components friendly for release and lower the anbaric assembler cost since it's so bad...

**Comment by SqFKYo** [comment]
Should be good enough for release, merging to dev.

**Pull request merged**
